variables:
  NPM_PUBLISH_TOKEN: $SPW_NEXUS_NPM_PRIVATE_TOKEN
  NPM_PUBLISH_REGISTRY: $SPW_NEXUS_NPM_PRIVATE_REGISTRY
  SONAR_HOST_URL: $SPW_SONAR_HOST_URL
  SONAR_TOKEN: $SPW_SONAR_TOKEN
  SONAR_PROJECT_KEY: $CI_PROJECT_NAME
  CNB_REGISTRY_SNAPSHOT_USER: $CI_REGISTRY_USER
  CNB_REGISTRY_SNAPSHOT_PASSWORD: $CI_REGISTRY_PASSWORD
  CNB_REGISTRY_RELEASE_USER: $SPW_NEXUS_USER
  CNB_REGISTRY_RELEASE_PASSWORD: $SPW_NEXUS_PASSWORD

stages:
  - build
  - test
  - package-build
  - package-test
  - deploy
  - publish


include:
  - component: $CI_SERVER_FQDN/devsecops/to-be-continuous/angular/gitlab-ci-angular@4.9.1
    inputs:
      cli-image: "$SPW_NEXUS_REGISTRY/trion/ng-cli-karma:18.2.1"
      npm-config-registry: $SPW_NEXUS_NPM_REGISTRY
      test-args: test --code-coverage --reporters progress,junit,sonarqubeUnit --watch=false --no-progress
      lint-args: lint --force
      publish-enabled: false # As it's an application (not a package)

  - component: $CI_SERVER_FQDN/devsecops/to-be-continuous/sonar/gitlab-ci-sonar@4.2.3

  - component: "$CI_SERVER_FQDN/devsecops/to-be-continuous/gitleaks/gitlab-ci-gitleaks@2.6"

  - component: $CI_SERVER_FQDN/devsecops/to-be-continuous/cnb/gitlab-ci-cnb@2.4.2
    inputs:
      builder-image: "$SPW_NEXUS_REGISTRY/heroku/builder:24"
      trivy-image: $SPW_NEXUS_REGISTRY/aquasec/trivy:latest
      trivy-security-level-threshold: CRITICAL
      trivy-args: "--offline-scan --ignore-unfixed"
      trivy-db-repository: $SPW_NEXUS_REGISTRY/aquasecurity/trivy-db
      trivy-java-db-repository: $SPW_NEXUS_REGISTRY/aquasecurity/trivy-java-db
      skopeo-image: $SPW_NEXUS_REGISTRY/skopeo/stable:latest
      release-image: $SPW_NEXUS_DOCKER_PRIVATE_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
      prod-publish-strategy: none # Disable publish on main branch

  - component: "$CI_SERVER_FQDN/devsecops/to-be-continuous/semantic-release/gitlab-ci-semrel@3.11"
    inputs:
      commit-spec: "conventionalcommits"
      # tag-format: "$${version}"

sonar:
  needs:
    - job: ng-build
      artifacts: true
    - job: ng-lint
      artifacts: true